### ISSUE TITLE
Removed wired save confirmation message

### ISSUE THREAD

**Issue by tymydes** [LilithRainbows/HabboAirPlus#1]
I just wanted to only remove the wired save confirmation message. may I know which path / class name is it in the swf?

**Comment by LilithRainbows** [comment]
![image](https://user-images.githubusercontent.com/44578053/177941077-1ac6ed27-54dd-4e83-81d2-5be273f986f3.png)
Replace that line with update();

**Comment by tymydes** [comment]
thanks!
