### ISSUE TITLE
Alert Error!

### ISSUE THREAD

**Issue by HeyReaz** [LilithRainbows/HabboAirPlus#14]
Cant use anymore after a maintenance. ;c

(Join FBI in Habbo, if u wanna e-meet me). ;idle

**Comment by NoxAccipiter** [comment]
I'm getting the same alert error, on the loading screen the loading bar just keeps repeating and doesn't load the client at all. for me the bar gets stuck at 60% and in the top left the alert box is showing, tried clicking the x etc, and nothing happens.

**Comment by Legitti** [comment]
Same error, please update 🔥

**Comment by Legitti** [comment]
Got the error again, please update 🔥

**Comment by LilithRainbows** [comment]
> Got the error again, please update 🔥

Try again, its working.

**Comment by Legitti** [comment]
> > Got the error again, please update 🔥
> 
> Try again, its working.

It is actually, must of been busy people login for the LTD or something 🤘🏻
