### ISSUE TITLE
Delay in sending messages

### ISSUE THREAD

**Issue by igorduxo** [LilithRainbows/HabboAirPlus#16]
I have so much delay when I or even other people send messages in the room, it takes like 15 seconds to appear, how can i fix this?

**Comment by LilithRainbows** [comment]
Hi, that was a server issue, not a client bug 🥰
It works good now?

**Comment by LilithRainbows** [comment]
> Hi, that was a server issue, not a client bug 🥰 It works good now?

Update: It seems that it could be a client error, it happens when old chat style is selected, I will check it.

**Comment by LilithRainbows** [comment]
> > Hi, that was a server issue, not a client bug 🥰 It works good now?
> 
> Update: It seems that it could be a client error, it happens when old chat style is selected, I will check it.

Update 2: It seems that fps values higher than 120 cause that issue if old chat style is selected.
