### ISSUE TITLE
Works great, few questions

### ISSUE THREAD

**Issue by Legitti** [LilithRainbows/HabboAirPlus#2]
This is amazing, no issues so far!
I have few questions, however;

1. How can I remove the auto-launch, in case I ever need to go back?
2. What does this "AutoClick button added to furni menu" mean, I couldn't find such a button?
3. What is the :playing command for? Is it like an auto clicker or what it does?
4. What do you suggest to use, CPU, DirectX or GPU for the launcher? What does the normal AIR version use by default?

Thanks for the great updates and support!

**Comment by Legitti** [comment]
> Hi, I'll answer your questions.
> 
> 1. Open the original Habbo Launcher, click on Help > Remove all game installations. Then go to the `C:\Users\XXXXX\AppData\Roaming\Habbo Launcher\downloads\air\XX` folder, rename the `HabboAir.swf` file to something like `HabboAirBackup.swf`. Then download the latest Plus available swf [here](https://github.com/LilithRainbows/HabboAirPlus/blob/main/HabboAir.swf) and place it in the same folder. Whenever you want to go back to the original client, just rename the Plus one to something different, and the original one to `HabboAir.swf`, and vice versa.
> 2. You need to use the latest swf version, which is available [here](https://github.com/LilithRainbows/HabboAirPlus/blob/main/HabboAir.swf). The one available in the releases section isn't updated. Then you may need to use the `:autoclick` command to enable the feature.
> 3. It activates an invisible freeze helmet in your user that allows you to click behind users and so on without hassle, ideal for playing games.
> 4. The default one uses CPU. I'd recommend to stick with CPU as that's how it's intented to be used. However, you could try the other options to see which one runs better in your end.

Oh, I can install this version too over the official one like the previous version? I used the HabboCustomLauncher.exe to auto-start it and was wondering how to remove that, and the :autoclick is not also working with that. 

If I replace the latest .swf, I don't need to replace any other files (wondering cos the releases version had many more files other than just .swf) but then again the previous version worked like that too I think.

**Comment by LilithRainbows** [comment]
> This is amazing, no issues so far! I have few questions, however;
> 
> 1. How can I remove the auto-launch, in case I ever need to go back?
> 2. What does this "AutoClick button added to furni menu" mean, I couldn't find such a button?
> 3. What is the :playing command for? Is it like an auto clicker or what it does?
> 4. What do you suggest to use, CPU, DirectX or GPU for the launcher? What does the normal AIR version use by default?
> 
> Thanks for the great updates and support!

1) Inside HabboCustomLauncher you can just click the "Register Habbo Protocol" button to enable/disable autolaunch.
2) You have to say :autoclick to enable that button and then click any compatible furni.
3) Its to avoid clicking users (click through)
4) CPU is the best render mode as far as i know.

**Comment by Legitti** [comment]
Thanks!

**Comment by LilithRainbows** [comment]
> Hi, I'll answer your questions.
> 
> 1. Open the original Habbo Launcher, click on Help > Remove all game installations. Then go to the `C:\Users\XXXXX\AppData\Roaming\Habbo Launcher\downloads\air\XX` folder, rename the `HabboAir.swf` file to something like `HabboAirBackup.swf`. Then download the latest Plus available swf [here](https://github.com/LilithRainbows/HabboAirPlus/blob/main/HabboAir.swf) and place it in the same folder. Whenever you want to go back to the original client, just rename the Plus one to something different, and the original one to `HabboAir.swf`, and vice versa.
> 2. You need to use the latest swf version, which is available [here](https://github.com/LilithRainbows/HabboAirPlus/blob/main/HabboAir.swf). The one available in the releases section isn't updated. Then you may need to use the `:autoclick` command to enable the feature.
> 3. It activates an invisible freeze helmet in your user that allows you to click behind users and so on without hassle, ideal for playing games.
> 4. The default one uses CPU. I'd recommend to stick with CPU as that's how it's intented to be used. However, you could try the other options to see which one runs better in your end.

Thanks for answer 💕
1) Yes, this is another available method, replacing original swf, like with my old clients.
2) Usually, everytime i update the swf i also update the release, so it will be updated too (on the releases page I specify the latest included commit) 💖

**Comment by LilithRainbows** [comment]
> > Hi, I'll answer your questions.
> > 
> > 1. Open the original Habbo Launcher, click on Help > Remove all game installations. Then go to the `C:\Users\XXXXX\AppData\Roaming\Habbo Launcher\downloads\air\XX` folder, rename the `HabboAir.swf` file to something like `HabboAirBackup.swf`. Then download the latest Plus available swf [here](https://github.com/LilithRainbows/HabboAirPlus/blob/main/HabboAir.swf) and place it in the same folder. Whenever you want to go back to the original client, just rename the Plus one to something different, and the original one to `HabboAir.swf`, and vice versa.
> > 2. You need to use the latest swf version, which is available [here](https://github.com/LilithRainbows/HabboAirPlus/blob/main/HabboAir.swf). The one available in the releases section isn't updated. Then you may need to use the `:autoclick` command to enable the feature.
> > 3. It activates an invisible freeze helmet in your user that allows you to click behind users and so on without hassle, ideal for playing games.
> > 4. The default one uses CPU. I'd recommend to stick with CPU as that's how it's intented to be used. However, you could try the other options to see which one runs better in your end.
> 
> Oh, I can install this version too over the official one like the previous version? I used the HabboCustomLauncher.exe to auto-start it and was wondering how to remove that, and the :autoclick is not also working with that. (Edit: autoclick working now after update)
> 
> If I replace the latest .swf, I don't need to replace any other files (wondering cos the releases version had many more files other than just .swf) but then again the previous version worked like that too I think.

You dont  need to replace any other file in that case, the extra included files in the Release are the whole AIR client (same files that are located on %AppData%\Habbo Launcher\downloads\air when you officially download it)
