### ISSUE TITLE
Not working (fixed)

### ISSUE THREAD

**Issue by Legitti** [LilithRainbows/HabboAirPlus#20]
![Screenshot 2024-05-14 180502](https://github.com/LilithRainbows/HabboAirPlus/assets/41343618/4b84e16f-49bf-4e42-9755-c4eadb081bfb)

**Comment by Legitti** [comment]
![Uploading Screenshot 2024-05-14 183034.png…]()

**Comment by rafitamolin** [comment]
@Legitti It's working with no issues. You have to replace every file in `Habbo Launcher\downloads\air\XXX` with those included in the appropiate zip for your OS here: https://github.com/LilithRainbows/HabboAirPlus/releases/tag/latest then replace the `HabboAir.swf` with this one which is the latest version: https://github.com/LilithRainbows/HabboAirPlus/raw/main/HabboAir.swf

**Comment by Legitti** [comment]
Got it to work now with the latest update, it was working fine before so I dont know what happened but its fixed.

**Comment by LilithRainbows** [comment]
Sorry for the late response.
Yes, as rafita says you need to download full release, because the swf requires a higher air version (51)
