### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by soyungatito** [LilithRainbows/HabboAirPlus#22]
I keep receiving this message, do you know what it can be? 
"Initial content could not be loaded for this application. Try reinstalling or contact the published for assistance"

**Comment by LilithRainbows** [comment]
You have to download the full zip release at:
https://github.com/LilithRainbows/HabboAirPlus/releases/latest
And in case you want to replace the original client move all the files from the zip insteado of only HabboAir.swf

**Comment by soyungatito** [comment]
It worked, thank you <3
