### ISSUE TITLE
:wave Usefulness for the military branch of habbo

### ISSUE THREAD

**Issue by cleyssonsantos** [LilithRainbows/HabboAirPlus#27]
Command that makes the character wave nonstop, until the :wave is sent again

What do you say LilithRainbows? Would you do this favor for the hundreds of military personnel currently on habbo?

**Comment by Julianty123** [comment]
Its just an opinion, but why don't try using scheduler of G-Earth? I understand that you might feel more comfortable using everything from the client, but that's why G-Earth exists to make extension development "easier"

**Comment by cleyssonsantos** [comment]
It seems to be one, but I don't know about this solution. What would it be like to use "G-Earth" to turn on the wave function in the launcher without stopping on command?

**Comment by LilithRainbows** [comment]
> Command that makes the character wave nonstop, until the :wave is sent again
> 
> What do you say LilithRainbows? Would you do this favor for the hundreds of military personnel currently on habbo?

You can use the flood command, in this case ":flood o/" (without quotes) 🥰
And then you can disable it with just typing ":flood" (without quotes)

**Comment by cleyssonsantos** [comment]
Wow, nice.... thanks, served perfectly.
