### ISSUE TITLE
New Chat Bubbles

### ISSUE THREAD

**Issue by Legitti** [LilithRainbows/HabboAirPlus#3]
Habbo just added some new chat bubbles, but they dont show in AirPlus yet, any chance to add support?
https://nft.habbo.com/info/#modern_speech_bubbles

They are working with latest official classic client

**Comment by LilithRainbows** [comment]
They are fully working on the latest official air client? The people are saying that they cant select those bubbles.

**Comment by LilithRainbows** [comment]
I will wait until the nft bubbles to be fully functional because it is not easy to update it.

**Comment by Legitti** [comment]
Oh, they are functional on classic, not just selectable. Discord they said this: _"They can all be selected while using the Modern client, but please bear in mind they are visible to everyone on both the Modern AND Classic clients."_

So that sounds like there isn't even feature coming to classic to change them, just see them.

**Comment by LilithRainbows** [comment]
Its weird because i looked inside latest classic client code and they had coded it to make nft chat bubbles selectable, i think its bugged or bad implemented

**Comment by Legitti** [comment]
Yeah it looks so, hopefully you can implement something anyway :)

**Comment by LilithRainbows** [comment]
Soon 🥰
